--Создаем схему и назначаем владельца
create schema tinder authorization admin;

--Создаем таблицу genders  - пол
create table tinder.genders (
  id   int generated by default as identity primary key,
  description varchar
);

--Создаем таблицу search_objects - объект поиска
create table tinder.search_objects (
  id  int generated by default as identity primary key,
  description varchar not null
);

--Создаем таблицу persons - анкеты участников
create table tinder.persons(
  id int primary key,
  name varchar,
  gender int REFERENCES  tinder.genders(id),
  search_object int REFERENCES  tinder.search_objects(id),
  description varchar
);

--Создаем таблицу statuses  - статус
create table tinder.statuses (
  id   int generated by default as identity primary key,
  description varchar
);

--Создаем таблицу sympathies   - симпатии
create table tinder.sympathies(
  id int generated by default as identity primary key,
  who int REFERENCES  tinder.persons(id),
  whom int REFERENCES  tinder.persons(id),
  status int REFERENCES  tinder.statuses(id)
);
